In [2]:
# import important libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [3]:
# Load Dataset

path = r"C:\Users\EHU_HEALTH_TECHNICAL\Documents\Khing_FM_Data_Science\Data_Science\assets\ts-academy_datasets\housing.csv"

df = pd.read_csv(path)

In [4]:
# Explore the data set

print("Dataset shape:", df.shape   )

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nSummary statistics")
display(df.describe())

Dataset shape: (20640, 10)

Columns:
['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']

Data types:
longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity           str
dtype: object

Missing values:
longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Summary statistics

          longitude      latitude  ...  median_income  median_house_value
count  20640.000000  20640.000000  ...   20640.000000        20640.000000
mean    -119.569704     35.631861  ...       3.870671       206855.816909
std        2.003532      2.135952  ...       1.899822       115395.615874
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.800000     33.930000  ...       2.563400       119600.000000
50%     -118.490000     34.260000  ...       3.534800       179700.000000
75%     -118.010000     37.710000  ...       4.743250       264725.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

In [5]:
# Machine Learning try
# Split features and targets (Separate X and Y)

x = df.drop("median_house_value", axis=1)

y = df["median_house_value"]

print("\nFeatures:")
display(x.head())

print("\nTarget:")
display(y.head())

Features:

   longitude  latitude  ...  median_income  ocean_proximity
0    -122.23     37.88  ...         8.3252         NEAR BAY
1    -122.22     37.86  ...         8.3014         NEAR BAY
2    -122.24     37.85  ...         7.2574         NEAR BAY
3    -122.25     37.85  ...         5.6431         NEAR BAY
4    -122.25     37.85  ...         3.8462         NEAR BAY

[5 rows x 9 columns]

Target:

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [6]:
# Identify categorical and numerical columns

numerical_features = [
    "longitude",
    "latitude",
    "housing_median_age",
    "total_rooms",
    "total_bedrooms",
    "population",
    "households",
    "median_income"
]

categorical_features = [
    "ocean_proximity"
]

In [8]:
# split the data into training and testing sets

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining set shape:", x_train.shape)
print("Testing set shape:", x_test.shape)

Training set shape: (16512, 9)
Testing set shape: (4128, 9)